### ISSUE TITLE
VM network hang and panic on restart

### ISSUE THREAD

**Issue by jlujan** [lima-vm/socket_vmnet#29]
Observing loss of connectivity to a lima VM after several hours using VZ and vmnet shared network. VM fails to `stop` cleanly, requiring `limactl stop -f`. Subsequently starting the VM results in panic from gvisor-tap-socket. A second `stop -f` and start results in successful VM boot. 

```
$ limactl start  
INFO[0000] Using the existing instance "default"        
INFO[0000] Hint: To create another instance, run the following command: limactl start --name=NAME template://default 
INFO[0000] Starting socket_vmnet daemon for "shared" network 
INFO[0000] Attempting to download the nerdctl archive from "https://github.com/containerd/nerdctl/releases/download/v1.1.0/nerdctl-full-1.1.0-linux-arm64.tar.gz"  digest="sha256:3b613a1be5a24460c44bb93a3609b790ada94e06efd1a86467d45bec7da8b449"
INFO[0000] Using cache "/Users/jlujan/Library/Caches/lima/download/by-url-sha256/c69be86b3e48430e3d687d54361cf15b90e2c067fae6a294ca6292d41f42bf0e/data" 
WARN[0000] [hostagent] Failed to detect CPU features. Assuming that AES acceleration is not available. 
INFO[0000] [hostagent] Starting VZ (hint: to watch the boot progress, see "/Users/jlujan/.lima/default/serial.log") 
INFO[0000] SSH Local Port: 60022                        
INFO[0000] [hostagent] panic: runtime error: invalid memory address or nil pointer dereference 
INFO[0000] [hostagent] [signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100c339bc] 
INFO[0000] [hostagent] goroutine 97 [running]:          
INFO[0000] [hostagent] github.com/containers/gvisor-tap-vsock/pkg/tap.(*Switch).Accept 
INFO[0000] [hostagent] 0x140000d6100, {0x101219798, 0x140000520c0}, {0x101221648, 0x140001281f8}) 
INFO[0000] [hostagent] 	/Users/jlujan/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containers/gvisor-tap-vsock@v0.4.1-0.20220920072955-5b1aff8ba743/pkg/tap/switch.go:83 +0x4c 
INFO[0000] [hostagent] github.com/containers/gvisor-tap-vsock/pkg/virtualnetwork.(*VirtualNetwork).AcceptBess(...) 
INFO[0000] [hostagent] 	/Users/jlujan/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/containers/gvisor-tap-vsock@v0.4.1-0.20220920072955-5b1aff8ba743/pkg/virtualnetwork/bess.go:9 
INFO[0000] [hostagent] github.com/lima-vm/lima/pkg/networks.run.func1() 
INFO[0000] [hostagent] 	/private/tmp/lima-20230209-37513-1rntxz9/pkg/networks/gvisor.go:90 +0x64 
INFO[0000] [hostagent] golang.org/x/sync/errgroup.(*Group).Go.func1() 
INFO[0000] [hostagent] 	/Users/jlujan/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c 
INFO[0000] [hostagent] created by golang.org/x/sync/errgroup.(*Group).Go 
INFO[0000] [hostagent] 	/Users/jlujan/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 
INFO[0000] [hostagent] 0xa4                             
FATA[0000] host agent process has exited: exit status 2 
```

limactl version HEAD-eb49205
M2 MacBook Air 
Ventura (13.1)

lima.yaml
```
vmType: "vz"
cpus: 4
memory: "12GiB"

...

networks:
  - lima: shared
  - vzNAT: true

mounts:
  - location: "~"
    writable: true
mountType: "virtiofs"

containerd:
  system: false
  user: true

portForwards:
  - guestSocket: "/run/user/{{.UID}}/buildkit-default/buildkitd.sock"
    hostSocket: "{{.Dir}}/sock/buildkitd.sock"
```

**Comment by balajiv113** [comment]
@jlujan 
Yes, this is a issue mostly in lima vz driver itself not related to socket_vmnet

Mostly its same as this issue
https://github.com/lima-vm/lima/issues/1200
